# Use a smaller base image for the final stage
FROM node:lts-alpine3.20 AS build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json first to leverage caching
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the project
RUN npm run build --no-cache

# Final stage with a smaller base image
FROM node:lts-alpine3.20

# Install 'serve' globally
RUN npm install -g serve

# Copy built files from the build stage
COPY --from=build /app/dist /app/dist

# Expose the port the app runs on
EXPOSE 5000

# Run the app
CMD ["serve", "-s", "app/dist", "-l", "5000"]