FROM node:lts-alpine3.20

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN npm install

# Install 'serve' globally
RUN npm install -g serve

# Expose the port the app runs on
EXPOSE 5000

# Run the app
CMD ["serve", "-s", "dist", "-l", "5000"]