version: "3.9"

services:
  frontend:
    container_name: frontend_container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"

volumes:
  data:
    driver: local
