FROM node:lts

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN npm install

# Set Env
ENV NODE_ENV production
EXPOSE 3000

# Cmd script
RUN npm run build
CMD ["serve", "-s", "dist"]