name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      # Build Docker image in GitHub Actions
      - name: Build Docker Image
        run: |
          docker build -t my-app-image:latest  -f ./DockerFile .

      # Save the Docker image as a tar file
      - name: Save Docker Image as Tar File
        run: |
          docker save my-app-image:latest -o my-app-image.tar

      # Upload the Docker tar file as an artifact (optional if needed)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: my-app-image.tar

      # Create EC2 private key file
      - name: Create EC2 private key file
        shell: bash
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$EC2_PRIVATE_KEY" > ec2_private_key.pem
          chmod 400 "ec2_private_key.pem"

      # Transfer Docker image tar file to EC2
      - name: Copy Docker Image to EC2
        shell: bash
        run: |
          scp -i ec2_private_key.pem -o StrictHostKeyChecking=no my-app-image.tar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/my-app-image.tar

      # Deploy on EC2
      - name: Deploy to EC2
        run: |
          ssh -i ec2_private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          docker load -i ~/my-app-image.tar &&
          docker compose -f ~/docker-compose.yml down &&
          docker compose -f ~/docker-compose.yml up -d --build
          "
